/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/rawmodel/tailwindcss-logo.glb --transform 
Files: public/rawmodel/tailwindcss-logo.glb [155.83KB] > C:\Users\USER\Desktop\mine\o-dada_portfolio\tailwindcss-logo-transformed.glb [15.24KB] (90%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/tailwindcss-logo-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.tailwindcss.geometry} material={materials.blue} />
    </group>
  )
}

useGLTF.preload('/tailwindcss-logo-transformed.glb')
