/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/rawmodel/ts-logo.glb --transform 
Files: public/rawmodel/ts-logo.glb [358.67KB] > C:\Users\USER\Desktop\mine\o-dada_portfolio\ts-logo-transformed.glb [24.44KB] (93%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ts-logo-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.TypeScriptsvg001.geometry} material={materials.blue} />
      <mesh geometry={nodes.TypeScriptsvg001_1.geometry} material={materials.white} />
    </group>
  )
}

useGLTF.preload('/ts-logo-transformed.glb')
